Fix generate WSDL
```php
<?php

use conquer\services\WsdlGenerator;
use yii\web\Controller;

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

class TestController extends Controller
{
    /**
     * @param TestA $test
     * @soap
     */
    public function test($test)
    {
    }
}

class TestA
{
    /**
     * @var string
     * @soap
     */
    public $property1;
    /**
     * @var \yii\helpers\ArrayHelper
     * @soap
     */
    public $property2;
}

$generator = new WsdlGenerator();
$generator->bindingStyle = WsdlGenerator::STYLE_DOCUMENT;
$wsdl = $generator->generateWsdl(TestController::className(), '');
```

caused:
Fatal error: Uncaught exception 'ReflectionException' with message 'Class /yii/helpers/ArrayHelper does not exist' in /app/vendor/conquer/services/WsdlGenerator.php on line 383